spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  api-docs:
    enabled: false
---
spring:
  application:
    name: hpz-gateways
  profiles:
    active:
    group:
      dev:
        - dev
        - api-docs
  jmx:
    enabled: false
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      pool:
        core-size: 2
        max-size: 50
      thread-name-prefix: hpz-gateways-task-
    scheduling:
      thread-name-prefix: hpz-gateways-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  output:
    ansi:
      consonle-avaible: true
server:
  servlet:
    session:
      cookie:
        http-only: true
springdoc:
  show-actuator: true

hypnoz:
  clientApp:
    name: 'hpz-gateways'
  mail:
    from: hpz-gateways@localhost
  api-docs:
    default-include-pattern: ${server.servlet.context-path:}/api/**
    management-include-pattern: ${server.servlet.context-path:}/management/**
    title: Hypnoz Gateways API
    description: Hypnoz Gateways API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license: unlicensed
    license-url:
  security:
      content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"
# ===================================================================